server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
    proxy_pass https://sisyphus-scheduler-production.up.railway.app;
    proxy_http_version 1.1;
    proxy_set_header Host sisyphus-scheduler-production.up.railway.app;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_ssl_server_name on;
    
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
}
}